### ISSUE TITLE
with autoproj v2 user_config variable in manifest is not being replaced anylonger

### ISSUE THREAD

**Issue by vbargsten** [rock-core/autoproj#135]
With autoproj v1, a definition in the manifest file such as

`
package_sets:
    - type: archive
      url: 'file://$TARBALL_DIR/my_package_set.tar.bz2'
`
with the user_config $TARBALL_DIR defined in init.rb worked perfectly fine. This allowed for instance to distribute a certain set of packages completely as tarballs. When bootstrapping, the user can modify the default path to the sources.
 
With autoproj v2 this fails at
`autoproj/variable_expansion.rb:53:in `block in single_expansion': cannot find a definition for $TARBALL_DIR (ArgumentError)`

I found the information gets lost in PackageSet.resolve_definition. When calling 
`vcs_spec = Autoproj.expand(vcs_spec, ws.manifest.constant_definitions)`
ws.manifest.constant_definitions is empty. ws.config.config on the other hand contains the variable with its configured value.

**Comment by doudou** [comment]
Indeed. This got lost. I'm not entirely sure why and if it's a good idea to put it back, I'll have to look at why it happened in the git history

In the meantime, you can pass the value in init.rb with

```
Autoproj.manifest.add_constant_definition('TARBALL_DIR' => Autoproj.config.get('TARBALL_DIR'))
```

**Comment by doudou** [comment]
Fixed by [2.1.0](https://github.com/rock-core/autoproj/releases/tag/v2.1.0)

**Comment by vbargsten** [comment]
Unfortunately still not working. It gets replaced now, but with a list of the variable's value and a boolean.
So, if I would have as before
```
package_sets:
    - type: archive url: 'file://$TARBALL_DIR/my_package_set.tar.bz2'
```

and do `aup`, the error is

**`bad URI(is not URI?): file://["/path/to/tarballs", true]/my_package_set.tar.bz2`**

**Comment by doudou** [comment]
Apologies. 2.1.2 should do the trick ... (This time with the associated unit tests ...)

**Comment by vbargsten** [comment]
Works. Thank you!
