### ISSUE TITLE
autoproj update selects old version of autoproj

### ISSUE THREAD

**Issue by planthaber** [rock-core/autoproj#391]
It seems like having `autoproj_version = ">= 2.0.0"` in the gemfile now selects autoproj version 2.0.3 (and also downgrades the installed version).

I had to set it manually to 2.1.0 in the .autoproj/Gemfile. remove the .autoproj/Gemfile.lock file and update to get the most recent version (2.16.0).

I already did a quick fix on the rock homepage version of autoproj_bootstrap: https://github.com/rock-core/rock-core.github.io/commit/bdf6a41899e257d95ec008c297504d3546b4f78b

But still don't have a good idea why this happened.

**Comment by planthaber** [comment]
https://github.com/rubygems/rubygems/issues/6226

**Comment by doudou** [comment]
Cf. #392 and #389

**Comment by doudou** [comment]
Should be fixed on master. Update autoproj_bootstrap or (better yet) use directly the one from git, e.g.

https://www.rock-robotics.org/rock-and-syskit/basics/installation.html

**Comment by planthaber** [comment]
Sadly github.io is not capable of 301/302 redirects, only http meta redirects.

The idea of having https://rock-robotics.org/autoproj_bootstrap is to have an easy to remember url for use with wget/curl.

While jekyll now supports http redirects (https://stackoverflow.com/questions/9276817/301-redirect-for-site-hosted-at-github), it can be used by browsers, but e.g. wget will not follow the redirect and download the generated html file containing the redirect.

I'll update the script on https://www.rock-robotics.org

**Comment by planthaber** [comment]
Renamed and reopened.

We still have this issue on existing workspaces where a .autoproj/Gemfile is present that used the old version of the bootstrap script.

These older Gemfiles are still having: `gem "autoproj", ">= 2.0.0"` in them

**Comment by doudou** [comment]
> The idea of having https://rock-robotics.org/autoproj_bootstrap is to have an easy to remember url for use with wget/curl.

It's a very rare action, and it's not very hard to remember "open the install page and copy/paste the URL". But suit yourself, we only use rock-and-syskit here.

**Comment by doudou** [comment]
> We still have this issue on existing workspaces where a .autoproj/Gemfile is present that used the old version of the bootstrap script.

Yes, we do. Which can be solved by communication - just sent 

At this stage, there's nothing I'm planning to do on Autoproj's side, so I'm closing.
